### ISSUE TITLE
Running commands doesn't work on Windows

### ISSUE THREAD

**Issue by targos** [Julien-R44/adonis-vscode-extension#10]
```
PS C:\git\project> cd /d "c:\git\project\api" && "node" ace playground  
ParserError: 
Line |
   1 |  cd /d "c:\git\project\api" && "node" ace playground
     |                                       ~~~
     | Unexpected token 'ace' in expression or statement.
```

**Comment by targos** [comment]
Another solution could be to run the command with `cmd.exe` (the `shell` option in child_process APIs).

**Comment by Julien-R44** [comment]
Thanks for the tip. So I did that, for the commands that run in the background. And for the commands sent in the integrated terminal of Vscode, we also open cmd.exe rather than the powershell
