### ISSUE TITLE
Running commands on click is risky

### ISSUE THREAD

**Issue by targos** [Julien-R44/adonis-vscode-extension#11]
I have a few commands that wipe out the data/db. A simple missclick can end up with bad consequences (even if it's just the local dev environment, time can be lost).

**Comment by Julien-R44** [comment]
Are you talking about custom commands or builtin migration commands? 

If you talk about custom commands, I see two possible solutions: 

- Add a configuration item in the extension, like "adonisjs.commandsToConfirm" in which we would list the name of the commands before which we want a confirmation prompt. This solution seems to me not very practical

- The other solution would be to add this prompt in front of all custom commands, but I'm not sure that's desirable either.

The last solution, which seems to me to be the most practical, would be that you add a "force" flag in your command. By adding a flag, when you will run the command via the extension, it will prompt you for the value you want to give to the "force" flag. This would avoid the missclick : we would have a prompt and not an immediate execution

In case `force` is false, you could add a prompt, in CLI, which asks you if you are sure you want to use this flag. This way you will be protected from missclick, but also from unwanted execution via the terminal ( can happen too I guess )

If you have any other suggestions or opinions on this I'd love to hear them !

**Comment by Julien-R44** [comment]
Or simply add a "promptToConfirmCommand" in the extension configuration. If enabled, then we'll always have a confirmation prompt before the commands. It's an extra step to execute a command, but maybe not that annoying

**Comment by targos** [comment]
> Are you talking about custom commands or builtin migration commands?

Both? `migration:rollback` is also risky for example.

> Add a configuration item in the extension, like "adonisjs.commandsToConfirm" in which we would list the name of the commands before which we want a confirmation prompt.

I don't like that

> The last solution, which seems to me to be the most practical, would be that you add a "force" flag in your command.

I'll probably do that as a last resort if we don't find another solution.

> If you have any other suggestions or opinions on this I'd love to hear them !

- What about switching from click to double-click to execute a command?
- Or keep single click, but not on the whole line. Instead, add an icon on the right like some other extensions do (thinking about Playwright to run a test).

**Comment by Julien-R44** [comment]
> What about switching from click to double-click to execute a command?
Not sure if this is possible with the Vscode API

> Or keep single click, but not on the whole line. Instead, add an icon on the right like some other extensions do (thinking about Playwright to run a test). 
Awesome, we'll keep this, it seems like the best solution to me.

I have a pretty busy week at work this week. I'm looking at all the issues this weekend! Thanks

**Comment by Julien-R44** [comment]
Now the commands must be executed by clicking on this icon
![image](https://user-images.githubusercontent.com/8337858/190861273-08aba00f-5b05-46b1-a323-040e4852276d.png)

**Comment by targos** [comment]
Thank you!
