### ISSUE TITLE
Add a button to open the custom command file

### ISSUE THREAD

**Issue by targos** [Julien-R44/adonis-vscode-extension#15]
It could be next to the "play" button. For example the Vitest and Playwright extensions have it:
![image](https://user-images.githubusercontent.com/2352663/199429383-cb938a08-56b4-4e69-8d31-6fe4e47dcbdd.png)

**Comment by Julien-R44** [comment]
Good idea, thanks! I'll take a look

**Comment by Julien-R44** [comment]
Took a while 😋 
implemented with the latest pre-release 1.1.6. Only for Adonis 6 projects
