### ISSUE TITLE
Issue loading extension in project

### ISSUE THREAD

**Issue by Doc94** [Julien-R44/adonis-vscode-extension#16]
## Package version
```
yarn list v1.22.19
├─ @adonisjs/ace@7.1.6
├─ @adonisjs/application@3.0.20
├─ @adonisjs/assembler@3.1.0
├─ @adonisjs/auth@5.0.2
├─ @adonisjs/bodyparser@5.0.6
├─ @adonisjs/config@2.0.2
├─ @adonisjs/core@5.0.4-preview-rc-2
│  └─ @adonisjs/validator@8.1.2
├─ @adonisjs/encryption@3.0.6
├─ @adonisjs/env@2.0.8
├─ @adonisjs/events@5.0.5
├─ @adonisjs/fold@7.0.8
├─ @adonisjs/generic-exceptions@3.0.1
├─ @adonisjs/hash@6.0.6
├─ @adonisjs/http-server@4.0.8
├─ @adonisjs/ioc-transformer@2.0.1
├─ @adonisjs/logger@3.0.3
├─ @adonisjs/lucid@9.0.3
├─ @adonisjs/mail@5.1.0
├─ @adonisjs/profiler@5.0.3
├─ @adonisjs/redis@5.0.9
├─ @adonisjs/require-ts@1.1.0
├─ @adonisjs/sink@4.2.1
├─ @adonisjs/validator@11.0.4
├─ @adonisjs/view@3.0.8
├─ adonis-preset-ts@1.0.4
├─ adonis-spreadsheet@1.0.1
│  ├─ @adonisjs/generic-exceptions@1.0.0
│  └─ @adonisjs/validator@4.0.9
├─ adonis5-cache@1.3.1
├─ adonis5-scheduler@2.0.2
└─ eslint-plugin-adonis@1.0.15
```

## Node.js and npm version
Node: v14.17.6
Yarn: 1.22.19

## Description
When open my project i get a error for the extension with the message `Cannot convert undefined or null to object` and not show any more information

**Comment by Julien-R44** [comment]
Yeah, you need to update your application, @adonisjs/core 5.0.4-preview-rc-2.1 was released more than 2 years ago. I don't have any plans to add backward compatibility for this version at the moment unfortunately

**Comment by Julien-R44** [comment]
Or, if you can share the repo with me, and I realize that there is not much to change, why not. Will close the issue in the meantime. feel free to provide further information
