### ISSUE TITLE
adding the extension on vscodium oss store

### ISSUE THREAD

**Issue by AbhimanyuAryan** [Julien-R44/adonis-vscode-extension#17]
vscodium is bloatware free VSCODE. A lot of extensions from massive companies popular for OSS are on https://open-vsx.org/ (some including RedHat, Gitlab etc)

I have just started learning Adonis and we use it for our product. It would be really helpful if the extension can be made available on opne-vsx store. It's not very difficult or time consuming task. It's a matter of just uploading vsix

**Comment by Julien-R44** [comment]
Any pointers on how to automate this? Are there any Github actions already built to do this easily?

**Comment by Julien-R44** [comment]
Here you go ! 

https://open-vsx.org/extension/jripouteau/adonis-vscode-extension

**Comment by Sliverside** [comment]
Hi, can you upgrade the open-vsx extension version ? I was trying to understand why it's doesn't work and after few hour debugging I find out that it wasn't the latest version :smile:. If someone got the same problem you can download the latest .vsix file on the Microsoft marketplace [here](https://marketplace.visualstudio.com/_apis/public/gallery/publishers/jripouteau/vsextensions/adonis-vscode-extension/latest/vspackage) or you can go on the extension page ([adonis-vscode-extension](https://marketplace.visualstudio.com/items?itemName=jripouteau.adonis-vscode-extension)) click on the "Version History" tab and click on the most recent download button.

> Any pointers on how to automate this? Are there any Github actions already built to do this easily?

here you go :
- publish using cli : https://github.com/eclipse/openvsx/wiki/Publishing-Extensions
- publish using Github Action : https://github.com/HaaLeo/publish-vscode-extension#readme

I can try to setup a Github Action but i never did it before.

Thank you for your work !
