### ISSUE TITLE
Whitespace bug in edge formatting for route name

### ISSUE THREAD

**Issue by tuanvu0995** [Julien-R44/adonis-vscode-extension#23]
I'm attempting to format the .edge file that contains `route` helper, which will introduce a space between `route("` and `name`. This will throw a route not found error.
See an example of this is shown below:

Before:
```edge
<a href="{{ route("users") }}">Users</a>
```

After:
```edge
<a href="{{ route(" users") }}">Users</a>
```

## Package version
AdonisJS Extension v0.9.1

## Node.js and npm version
Node v18.14.0
NPM 8.19.4

**Comment by Julien-R44** [comment]
Released in 0.9.2
