### ISSUE TITLE
Formatting does not preserve indents in tag blocks

### ISSUE THREAD

**Issue by phatmann** [Julien-R44/adonis-vscode-extension#25]
## Package version
1.1.7

## Node.js and npm version
Node: v16.20.0
NPM: 8.19.4

## Sample Code (to reproduce the issue)

This Edge code:

```
@section('body')
  <section class="section">
    <div>
      <h1 class="title">{{title}}</h1>
      <ul>
        <li>
          @if(isLoggedIn(session))
            <a href="/schedule">Go to my schedule</a>
          @else
            <a href="/verify">Sign In</a>
          @endif
        </li>
      </ul>
    </div>
  </section>
@end
```

loses its indentation when formatted:

```
@section('body')
<section class="section">
  <div>
    <h1 class="title">{{title}}</h1>
    <ul>
      <li>
        @if(isLoggedIn(session))
        <a href="/schedule">Go to my schedule</a>
        @else
        <a href="/verify">Sign In</a>
        @endif
      </li>
    </ul>
  </div>
</section>
@end
```

**Comment by Julien-R44** [comment]
Hey, yeah, we currently don't have autoformatting, and its probably out of scope for this extension. still waiting for a community initiative to take on this task. unfortunately i don't have the time to maintain such a thing at the moment

see : https://github.com/Julien-R44/adonis-vscode-extension/issues/20
