### ISSUE TITLE
Views in @unless tag not parsed correctly

### ISSUE THREAD

**Issue by phatmann** [Julien-R44/adonis-vscode-extension#26]
## Package version
1.1.7

## Node.js and npm version
Node: v16.20.0
NPM: 8.19.4

## Sample Code (to reproduce the issue)

This Edge code gives a "missing-view" warning:

```
@unless(['/verify', '/signin'].includes(request.url()))
```

while this semantically identical code is fine:

```
@if(!['/verify', '/signin'].includes(request.url()))
```

**Comment by Julien-R44** [comment]
Thanks for the issue!
Fixed and release as 1.1.8
