### ISSUE TITLE
Controllers not detected if in namespaced group

### ISSUE THREAD

**Issue by theRealPadster** [Julien-R44/adonis-vscode-extension#27]
I've got a namespaced group for some user-related controllers but when I switch to the pre-release version of the AdonisJS extension, it underlines the ones in the group with a "Missing controller" message: 
<img width="684" alt="image" src="https://github.com/Julien-R44/adonis-vscode-extension/assets/1565883/3de16484-efe7-4be6-b6f7-3056ecd3c9c8">

## Package version
v1.1.9

## Node.js and npm version
Using NVM with default node v20.0.0 and npm v9.6.4

## Sample Code (to reproduce the issue)
```ts
// Namespace the controllers so they're not all in the same folder
Route.group(() => {
  // Authentication (login/logout/register) routes
  Route.group(() => {
    // Log in page and post route
    Route.get('/login', 'AuthController.loginShow').as('login.show');
    Route.post('/login', 'AuthController.loginSubmit').as('login.submit');
    // Register in page and post route
    Route.get('/register', 'AuthController.registerShow').as('register.show');
    Route.post('/register', 'AuthController.registerSubmit').as('register.submit');
    // log out route
    Route.get('/logout', 'AuthController.logout').as('logout');
  }).as('auth');
}).namespace('App/Controllers/Http/Users');
```

**Comment by Julien-R44** [comment]
Yeah, dealing with that would require a lot of work: basically using an AST to statically analyze the file and extract the different namespaces. And knowing that with Adonis 6 we will have better ways of doing routing (we're going to use real javascript imports. No more magic strings), I don't intend to add or improve this part of the extension

On the other hand, having these little red "Missing controller" lines is annoying. I'm thinking of removing the warning or at least adding an option to disable these warnings. Gonna work on that asap. We can track this in another issue if needed

**Comment by francyleo** [comment]
It's been over 2 years and they still haven't solved it?

You don't even need to be in a group to have this problem, just by *organizing* it (putting the routes in files other than routes.ts) it doesn't work.

What a shot in the foot, to have to choose a framework that depends on extensions to help the development flow and in the end none of it works properly.
