### ISSUE TITLE
Formatting ident stop working

### ISSUE THREAD

**Issue by brunojoao** [Julien-R44/adonis-vscode-extension#28]
There was another .edge extension for vscode, this all happens, whenever vscode updates the identification it stops working, I don't know what I could do to get around this problem, it was working correctly. =/

## vscode version
1.83.0

## Version extension
0.9.2

**Comment by Julien-R44** [comment]
Hey, this extension does not manage the formatting of .edge files

See : https://github.com/Julien-R44/adonis-vscode-extension/issues/20#issuecomment-1460543255
