### ISSUE TITLE
v1.2 broke some Edge template features.

### ISSUE THREAD

**Issue by TDodgeCo** [Julien-R44/adonis-vscode-extension#31]
## Package version
1.2.0  | Adonis v5

## Node.js and npm version
Node: 18.16.0 | npm: 9.5.1

## Sample Code (to reproduce the issue)
Just update the extension to 1.2.0 and try to format or autocomplete. 

Here's an example of attempting to stub out an `<a>` tag:
https://i.imgur.com/o3fvVOb.png

Here's the response received when attempting to auto format the file with `alt + shift + f`
https://i.imgur.com/kGMie1C.png

Reverting back to the previous version solved these issues for me.

## BONUS (a sample repo to reproduce the issue)
N/A

**Comment by Julien-R44** [comment]
Should be fixed with version 1.5.0 of the Edge Extension

Please open issues on this repo if you are encountering any other issues related to Edge : https://github.com/edge-js/edge-vscode
