### ISSUE TITLE
The requested module 'node:module' does not provide an export named 'register'

### ISSUE THREAD

**Issue by vijeeshin** [Julien-R44/adonis-vscode-extension#34]
file:///Users/xxx/xxx/ace.js:22
import { register } from 'node:module'

The requested module 'node:module' does not provide an export named 'register'

**Comment by RomainLanz** [comment]
Update your Node version.

**Comment by vijeeshin** [comment]
Using node v20.11.0

**Comment by vijeeshin** [comment]
I am getting result for: node ace

Options:
  --ansi|--no-ansi    Force enable or disable colorful output
  --help              View help for a given command ,

**Comment by vijeeshin** [comment]
While using extension, this is the result:
Error: Command failed with exit code 1: node --dns-result-order=ipv4first ace list:routes --json
file:///Users/xxxx/xxxx/ace.js:22
import { register } from 'node:module'
         ^^^^^^^^
SyntaxError: The requested module 'node:module' does not provide an export named 'register'
    at ModuleJob._instantiate (node:internal/modules/esm/module_job:128:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:194:5)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:385:24)
    at async loadESM (node:internal/process/esm_loader:88:5)
    at async handleMainPromise (node:internal/modules/run_main:61:12)

**Comment by Julien-R44** [comment]
As Romain said, please upgrade your Node version

![image](https://github.com/Julien-R44/adonis-vscode-extension/assets/8337858/73d3f996-8592-4faf-b0d2-d50b70140ea3)

https://docs.adonisjs.com/guides/installation

**Comment by vijeeshin** [comment]
Ok Thanks
