### ISSUE TITLE
List routes command fails

### ISSUE THREAD

**Issue by targos** [Julien-R44/adonis-vscode-extension#4]
Happy to provide more information if you need it. `node ace list:routes` (with or without --json) works fine in the terminal.

<img width="555" alt="image" src="https://user-images.githubusercontent.com/2352663/166103852-5526abfd-72ca-45c9-9975-1d04b2bfbea5.png">

**Comment by Julien-R44** [comment]
It's weird, I can't really say why.
Is it possible for you to share the return of `node ace list:routes --json`? 

I can't reproduce the problem, either on Mac/Linux/Windows and I tried on several projects with different routes
( Thank you for taking the time to write all these issues 👍 )

**Comment by targos** [comment]
I can't really share it (it's private customer's code)

**Comment by targos** [comment]
Would there be a way for me to debug it locally? I'd like to add a breakpoint where the JSON.parse happens.

**Comment by Julien-R44** [comment]
The only way I can see right now would be to clone the repo and debug locally 😓

That said, it's very simple, basically: clone, npm install, add a breakpoint here: https://github.com/Julien-R44/adonis-vscode-extension/blob/7c412cbb237577a20a8a8a629de86f3bcad59b56/src/commands/list/Routes.ts#L31

Then press F5, it opens a new VSCode editor, open the problematic project in it, and do the ListRoutes thing

Sorry to ask you this, I guess it's just a small error 😓
However, no hurry if you don't have much time right now, I'll investigate a bit more on my side.

**Comment by targos** [comment]
What I found is that the result of the command is truncated (the end of the output is missing).
I'm not sure it will work (and I don't have more time now to try, maybe this evening), but I suggest that instead of doing `cd xxx && command`, you run the command using the `cwd` option
https://github.com/Julien-R44/adonis-vscode-extension/blob/f559b9268094e98290415587b8ff621b967edb7e/src/commands/BaseCommand.ts#L183-L187
https://nodejs.org/dist/latest-v18.x/docs/api/child_process.html#child_processexeccommand-options-callback

**Comment by targos** [comment]
I tried it (and I think it's better that way regardless), but that doesn't fix the problem.

**Comment by targos** [comment]
This is probably https://github.com/nodejs/node/issues/19218

**Comment by targos** [comment]
If I understand the problem correctly, the bug is actually in `ace`/AdonisJS, where `process.exit` is called while there is still something in the queue to be printed to stdout.

**Comment by targos** [comment]
@thetutlage is that possible?

**Comment by thetutlage** [comment]
@targos Maybe. Since you are debugging it all locally. Can you please add `stayAlive` property to this command https://github.com/adonisjs/core/blob/develop/commands/ListRoutes/index.ts#L62

**Comment by Julien-R44** [comment]
Thank you for investigating Michaël 

On my side, impossible to reproduce the problem, even with more than +500 different defined routes and thus a consequent output 🤔

**Comment by targos** [comment]
Are you on a Mac @Julien-R44 ?

**Comment by Julien-R44** [comment]
Mostly on Windows, but I have a mac and ubuntu on hand and have been unable to reproduce the bug on all three different configurations. You are experiencing this bug on Windows, right?

**Comment by targos** [comment]
No, I can only reproduce on Mac. No issues with the same project on Windows.

**Comment by Julien-R44** [comment]
Ok finally the problem occurs under my mac with my file containing more than 500 routes !

@thetutlage I was able to add `stayAlive` to true on ListRoutes, and indeed the problem disappears.

I'll read more about it to better understand the problem, but if you have an idea how to fix it, I'll take it !

**Comment by thetutlage** [comment]
`stayLive` is an okay to use, since it waits for the Node process to shutdown gracefully. Just make sure to all `await this.application.shutdown()` inside the command `run` method.

**Comment by Julien-R44** [comment]
Future readers, if you encounter the same issue : 
Upgrade adonisjs/core to at least 5.7.6 and run `node ace generate:manifest`

**Comment by thetutlage** [comment]
Is it true that this is indeed an issue https://github.com/nodejs/node/issues/19218, which is caused by exiting the process with `process.exit` call? 

And the only available solution right now is to let the process shutdown gracefully?
