### ISSUE TITLE
Do not show AdonisJS commands when no AdonisJS project is detected

### ISSUE THREAD

**Issue by targos** [Julien-R44/adonis-vscode-extension#5]
I don't know if it's possible, but currently if you try to run an AdonisJS command in a project without AdonisJS, it ends up in an error:

![image](https://user-images.githubusercontent.com/2352663/166210813-72a8083d-ddec-4b29-bcdc-478bce41b237.png)

**Comment by Julien-R44** [comment]
Thanks for reporting !
