### ISSUE TITLE
Error "Unexpected token S in JSON at position 0" after v0.6.0 update

### ISSUE THREAD

**Issue by sowind** [Julien-R44/adonis-vscode-extension#9]
## Package version
v0.6.0

## Node.js and npm version
Node: v18.7.0
Npm: 8.15.0
Installed through NVM

## Description
Hello. I'm getting these errors after yesterday update. My routes are completely standard, I didn't change their location and etc. 
`node ace list:routes` works just fine.
I'm using **vscode remote development** extension.

![image](https://user-images.githubusercontent.com/7592081/186078926-c8984c03-a8fe-4303-ba9d-71fba302d237.png)
![image](https://user-images.githubusercontent.com/7592081/186078976-49c7aa1d-eb99-4a7f-b011-3baf1d656469.png)

App/Start/Routes.ts
```
import Route from '@ioc:Adonis/Core/Route';
import HealthCheck from '@ioc:Adonis/Core/HealthCheck';
import './routes/users';

Route.get('/', async () => {

  return { hello: 'world' }

});

Route.get('test', async () => {

  return { app: 'is working.' }
  
});

Route.get('health', async ({ response }) => {
  const report = await HealthCheck.getReport()

  return report.healthy
    ? response.ok(report)
    : response.badRequest(report)
});
```

App/Start/routes/users.ts
```
import Route from '@ioc:Adonis/Core/Route';

Route.group(() => {

  Route.group(() => {

    Route.get('login', 'SignInController.create');

    Route.post('login', 'SignInController.store');

    Route.post('register', 'SignUpController.store');

    Route.get('logout', 'SignInController.destroy');

    Route.get('forgot', 'ForgotPasswordController.getForm');

    Route.post('forgot', 'ForgotPasswordController.postEmail');

    Route.get('forgot/:hash', 'ForgotPasswordController.checkHash');

    Route.post('forgot/:hash', 'ForgotPasswordController.changePassword');

  }).prefix('web');

}).prefix('u');

Route.resource('u', 'UsersController')
  .except(['index', 'create', 'store'])
  .paramFor('u', 'userId');
```

Thanks in advance.

**Comment by Julien-R44** [comment]
Hello! Thanks for the feedback

I'm not familiar with VScode Remote at all, I'll have to set up a configuration like yours.

With VScode remote, are you developing on WSL, or on a remote server? 

If you run a `node ace list:routes --json` on your project, do you get the right output?

Do you use several workspaces in your vscode, or a monorepo?

**Comment by Julien-R44** [comment]
Okay well that's weird ! 

If it happens again, just try refreshing the routes from Tree View and see if that fixes it : 
![image](https://user-images.githubusercontent.com/8337858/186233497-c139ea98-5634-4366-a20f-6e99897e7e17.png)

And feel free to reopen the issue if it happens again ! Thanks
